#!/usr/bin/env python3
"""Figures for this concept's explainer.qmd.

    .venv/bin/python <concept>/figs/make_figs.py

Every figure the explainer references MUST be generated by this script — no stubs, ever
(a missing PNG hard-fails the PDF render). Replace the example below with the concept's
real diagram(s); keep one function per figure.
"""
import os
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))


def make():
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.text(0.5, 0.5, "replace me with the concept's real diagram", ha="center", va="center")
    ax.axis("off")
    out = os.path.join(HERE, "example.png")
    fig.savefig(out, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print("wrote", out)


if __name__ == "__main__":
    make()
