#!/usr/bin/env bash
# Compare swiftml (our from-scratch compiler) against the real swiftc on classical programs.
#
#   from course/ :   bash comparisons/run.sh            # human table
#                    bash comparisons/run.sh --md       # write comparisons/RESULTS.md
#
# For each program we build with BOTH compilers at -Onone and -O, run all four binaries, and check
# that swiftml's stdout+exit matches swiftc's at each optimization level (the project's parity bar).
#
# NOTE: the shipped course tree is RED-by-design (every concept ships skeletons with TODO holes), so
# this swaps concept-40's solution in to make swiftml9 — the full-language LLVM-path binary — fully
# functional, runs the suite, then restores the skeleton.
set -u
cd "$(dirname "$0")/.."
eval "$(opam env)" 2>/dev/null
MD=0; [ "${1:-}" = "--md" ] && MD=1
SOL=phase8-arm64-backend/40-macros
cp "$SOL/macros.ml" /tmp/macros_skel.ml 2>/dev/null
cp "$SOL/solution/macros.ml" "$SOL/macros.ml"
dune build 2>/dev/null
tmp=$(mktemp -d)
pass=0; fail=0
out=/tmp/cmp_table.txt; : > "$out"
printf "%-26s %-8s %-8s %s\n" "program" "-Onone" "-O" "notes" >> "$out"
printf "%-26s %-8s %-8s %s\n" "-------" "------" "--" "-----" >> "$out"
for f in comparisons/programs/*.swift; do
  name=$(basename "$f")
  swiftc      "$f" -o "$tmp/sc0" 2>/dev/null && sc0=$("$tmp/sc0" 2>&1; echo "x$?") || sc0="ERR"
  swiftc -O   "$f" -o "$tmp/sc1" 2>/dev/null && sc1=$("$tmp/sc1" 2>&1; echo "x$?") || sc1="ERR"
  if dune exec swiftml9 -- build "$f" -o "$tmp/ml0" >/tmp/e 2>&1; then ml0=$("$tmp/ml0" 2>&1; echo "x$?"); else ml0="BUILDFAIL"; fi
  if dune exec swiftml9 -- build -O "$f" -o "$tmp/ml1" >/tmp/e 2>&1; then ml1=$("$tmp/ml1" 2>&1; echo "x$?"); else ml1="BUILDFAIL"; fi
  r0=MATCH; [ "$ml0" != "$sc0" ] && r0=DIFFER
  r1=MATCH; [ "$ml1" != "$sc1" ] && r1=DIFFER
  printf "%-26s %-8s %-8s %s\n" "$name" "$r0" "$r1" "lines=$(echo "$sc0"|wc -l|tr -d ' ')" >> "$out"
  if [ "$r0" = MATCH ] && [ "$r1" = MATCH ]; then pass=$((pass+1)); else fail=$((fail+1)); fi
done
echo >> "$out"
echo "PASS=$pass  FAIL=$fail  (of $((pass+fail)))  — swiftml9 vs swiftc, -Onone and -O, stdout+exit" >> "$out"
cat "$out"
if [ "$MD" = 1 ]; then
  { echo "# swiftml vs swiftc — comparison results"; echo;
    echo "Generated by \`comparisons/run.sh --md\`. Each program is compiled by **swiftml9** (our";
    echo "from-scratch compiler, full-language LLVM path) and by **swiftc 6.3.2**, at \`-Onone\` and";
    echo "\`-O\`; we assert identical stdout **and** exit code at each level."; echo;
    echo '```'; cat "$out"; echo '```'; } > comparisons/RESULTS.md
  echo "wrote comparisons/RESULTS.md"
fi
cp /tmp/macros_skel.ml "$SOL/macros.ml" 2>/dev/null
rm -rf "$tmp"
